<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
    '序号'=> 'No.',
    '标题'=> 'Title',
    '简介'=> 'Introduction',
    '发布时间'=> 'Publishing Time',
    '状态'=> 'Status',
    '开始显示时间'=> 'Starting Time',
    '结束显示时间'=> 'Closing Time',
    '操作'=> 'Manipulate',
);