<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  '请输入你的用户名密码' => 'Please Enter Your Information',
  '用户名' => 'Username',
  '密码' => 'Password',
  '自动登录' => 'Remember me next time',
  '登录' => 'Login',
  '用户名不能为空!' => 'Please provide a valid username.',
  '密码不能为空!' => 'Please specify a password.',
  '密码不能小于5位数!' => 'Please specify a secure password.',
);